package com.pugicorn.spotifake_server.controller;


import com.pugicorn.spotifake_server.entity.Party;
import com.pugicorn.spotifake_server.mapper.PartyRepository;
import okhttp3.OkHttpClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Map;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/party") // This means URL's start with /demo (after Application path)
public class PartyController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PartyRepository partyRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody
    String addParty (@RequestBody Map<String, Object> payload,
                      HttpServletResponse serverResponse)
            throws IOException { OkHttpClient client = new OkHttpClient();
        return "";
    }

    @GetMapping(path="")
    public @ResponseBody
    Iterable<Party> getAllUsers(@RequestParam("name") String username) {
        // This returns a JSON or XML with the users
        return partyRepository.findAll();
    }

    @GetMapping(path="/{id}")
    public @ResponseBody
    void getUer(@PathVariable String id) {
        // This returns a JSON or XML with the users
    }
}